language: node_js
node_js: 
    - 'stable'
cache:
    directories:
        - 'node_modules'
before_install:
    - npm install -g @angular/cli
install:
    - npm install
branches:
    only: 
        - master
app: Squirrel-order-Management-system
