language: node_js
node_js: 
    - 'stable'
cache:
    directories:
        - 'node_modules'
before_install:
    - npm install -g @angular/cli
install:
    - npm install
branches:
    only: 
        - master
after_script:
    - chmod +x publish-pages.sh && ./publish-pages.sh
deploy:
    provider: heroku
    api_key:
        secure: MIGJAoGBAKY1mJtfyxF51Z8XSE4q/kLixEUegc4UGyP0lTH/URfJ3Yg7HzNwOXNg\nxWYtBWg8foI6H71J25iDGFYFA7ihY1GwDDlfd/RmYzBHD3nrVRdzYvvqKZgAfS9J\nvQnqfMVBRNYlP6osvgf394BvOTCr
    app: squirrel-order-management