language: node_js
node_js: 
    - 'stable'
cache:
    directories:
        - 'node_modules'
before_install:
    - npm install -g @angular/cli
install:
    - npm install
branches:
    only: master
deploy:
    provider: heroku
api_key:
    secure: 39e6ff68-9bb0-4615-909e-1ea1b1203712
app: Squirrel-order-Management-system
